sfdx-source/force-app/main/default/objects/Shared_Solar_System__c/Shared_Solar_System__c.object-meta.xml
<CustomObject>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/classes/triggerHandlers/SubscriptionsTriggerHandler.cls
/**
 * SubscriptionsTriggerHandler
 *
 * @group Trigger Handlers
 */
public inherited sharing class SubscriptionsTriggerHandler extends ApplicationSObjectDomain
{
    public SubscriptionsTriggerHandler(List<Subscription__c> records)
    {
        super(records);
    }

    public override void onAfterInsert()
    {
        validateEffectivityDates(getRecords());
    }

    public override void onAfterUpdate(Map<Id, SObject> existingRecords)
    {
        onChangeEffectivityDates();
    }

    private void onChangeEffectivityDates()
    {
        Set<Schema.SObjectField> fields = new Set<Schema.SObjectField>
        {
            Schema.Subscription__c.Start_Date__c,
            Schema.Subscription__c.End_Date__c
        };

        List<Subscription__c> changedRecords = getChangedRecords(fields);

        if (changedRecords.isEmpty() == false)
        {
            validateEffectivityDates(changedRecords);
        }
    }

    private void validateEffectivityDates(List<Subscription__c> records)
    {
        List<Subscription__c> existingSubscriptions =
            SubscriptionsSelector.newInstance().selectByCustomerAndSharedSolarSystem(records);

        Set<Id> recordIdsWithStartDateOverlap = new Set<Id>();
        Set<Id> recordIdsWithEndDateOverlap = new Set<Id>();

        for (Subscription__c record : records)
        {
            Boolean hasExistingSubscriptionWithStartDateOverlap =
                Subscriptions.newInstance(existingSubscriptions)
                    .selectByIdNotInValue(record.Id)
                    .selectByCustomer(record.Customer__c)
                    .selectBySharedSolarSystem(record.Shared_Solar_System__c)
                    .selectByStartDateLessThanOrEqualToValue(record.Start_Date__c)
                    .selectByEndDateGreaterThanOrEqualToValue(record.Start_Date__c)
                    .isNotEmpty();

            if (hasExistingSubscriptionWithStartDateOverlap)
            {
                recordIdsWithStartDateOverlap.add(record.Id);
            }

            Boolean hasExistingSubscriptionWithEndDateOverlap =
                Subscriptions.newInstance(existingSubscriptions)
                    .selectByIdNotInValue(record.Id)
                    .selectByCustomer(record.Customer__c)
                    .selectBySharedSolarSystem(record.Shared_Solar_System__c)
                    .selectByStartDateLessThanOrEqualToValue(record.End_Date__c)
                    .selectByEndDateGreaterThanOrEqualToValue(record.End_Date__c)
                    .isNotEmpty();

            if (hasExistingSubscriptionWithEndDateOverlap)
            {
                recordIdsWithEndDateOverlap.add(record.Id);
            }
        }

        Subscriptions.newInstance(records).selectById(recordIdsWithStartDateOverlap).addStartDateOverlapError();
        Subscriptions.newInstance(records).selectById(recordIdsWithEndDateOverlap).addEndDateOverlapError();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjects)
        {
            return new SubscriptionsTriggerHandler(sObjects);
        }
    }
}