sfdx-source/force-app/main/default/objects/Shared_Solar_System__c/Shared_Solar_System__c.object-meta.xml
<CustomObject>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  AND(TODAY() &gt;= Start_Date__c, TODAY() &lt;= End_Date__c),
  &apos;Active&apos;,
  &apos;Inactive&apos;
)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/SubscriptionsSelector.cls
/**
 * SubscriptionsSelector
 *
 * @group Selectors
 */
public class SubscriptionsSelector extends fflib_SObjectSelector
    implements ISubscriptionsSelector
{
    public static ISubscriptionsSelector newInstance()
    {
        return (ISubscriptionsSelector) Application.Selector.newInstance(Schema.Subscription__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField>
        {
            Schema.Subscription__c.Id,
            Schema.Subscription__c.Customer__c,
            Schema.Subscription__c.End_Date__c,
            Schema.Subscription__c.Name,
            Schema.Subscription__c.Shared_Solar_System__c,
            Schema.Subscription__c.Start_Date__c,
            Schema.Subscription__c.Status__c
        };
    }

    public Schema.SObjectType getSObjectType()
    {
        return Schema.Subscription__c.SObjectType;
    }

    public List<Subscription__c> selectById(Set<Id> ids)
    {
        return (List<Subscription__c>) selectSObjectsById(ids);
    }

    public List<Subscription__c> selectByCustomerAndSharedSolarSystem(List<Subscription__c> subscriptions)
    {
        Set<Id> customerIds = new Set<Id>();
        Set<Id> sharedSolarSystemIds = new Set<Id>();

        for (Subscription__c subscription : subscriptions)
        {
            customerIds.add(subscription.Customer__c);
            sharedSolarSystemIds.add(subscription.Shared_Solar_System__c);
        }

        return selectByCustomerAndSharedSolarSystem(customerIds, sharedSolarSystemIds);
    }

    public List<Subscription__c> selectByCustomerAndSharedSolarSystem(Set<Id> customerIds, Set<Id> sharedSolarSystemIds)
    {
        fflib_QueryFactory queryFactory =
            newQueryFactory(false, false, true)
                .setCondition('Customer__c IN :customerIds AND Shared_Solar_System__c IN :sharedSolarSystemIds');

        return Database.query(queryFactory.toSOQL());
    }
}