sfdx-source/force-app/main/default/objects/Shared_Solar_System__c/Shared_Solar_System__c.object-meta.xml
<CustomObject>
    <label>Shared Solar System</label>
    <nameField>
        <label>Shared Solar System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Solar Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/test/classes/selectors/SubscriptionsSelectorTest.cls
@IsTest
private class SubscriptionsSelectorTest
{
    @TestSetup
    private static void makeData()
    {
        Account accountRecord = new Account(Name = 'Orlando20221106');
        insert accountRecord;

        Shared_Solar_System__c sharedSolarSystemRecord = new Shared_Solar_System__c(
            Name = 'SunshineStateSolarSystem20221106'
        );
        insert sharedSolarSystemRecord;

        Subscription__c subscriptionRecord = new Subscription__c(
            Customer__c = accountRecord.Id,
            Shared_Solar_System__c = sharedSolarSystemRecord.Id,
            Start_Date__c = Date.newInstance(2001, 12, 4),
            End_Date__c = Date.newInstance(2002, 1, 4)
        );
        insert subscriptionRecord;
    }

    @IsTest
    private static void itShouldSelectById()
    {
        // given
        List<Subscription__c> initialRecords = [SELECT Id FROM Subscription__c ORDER BY Name ASC NULLS LAST];

        Set<Id> recordIds = new Set<Id> { initialRecords.get(0).Id };

        ISubscriptionsSelector selector = SubscriptionsSelector.newInstance();

        // when
        List<Subscription__c> finalRecords = selector.selectById(recordIds);

        // then
        System.assertEquals(false, finalRecords.isEmpty());
        System.assertEquals(initialRecords.get(0).Id, finalRecords.get(0).Id);
    }

    @IsTest
    private static void itShouldSelectByCustomerAndSharedSolarSystem()
    {
        // given
        List<Subscription__c> initialRecords = [
            SELECT Id, Customer__c, Shared_Solar_System__c
            FROM Subscription__c
            ORDER BY Name ASC NULLS LAST
        ];

        ISubscriptionsSelector selector = SubscriptionsSelector.newInstance();

        // when
        List<Subscription__c> finalRecords = selector.selectByCustomerAndSharedSolarSystem(initialRecords);

        // then
        System.assertEquals(false, finalRecords.isEmpty());
        System.assertEquals(initialRecords.get(0).Id, finalRecords.get(0).Id);
    }
}